### ISSUE TITLE
好酷的一键配置本地文件！本地文件能否可以自定义目录位置呀！

### ISSUE THREAD

**Issue by asong2022** [LinkScapeOfficial/LinkDown#1]
本地文件能否可以自定义目录位置，虽然改了位置之后，浏览器拓展的链接就要改了……

**Comment by TakumiBC** [comment]
不太明白“自定义目录位置”的意思呢... 请问能不能详细说说呢~

**Comment by asong2022** [comment]
这个不是安装在c盘吗，我想安装在自己指定的地方，，是不是有点麻烦，因为这样子浏览器拓展的配置就对应了

**Comment by TakumiBC** [comment]
是很麻烦，您可以在json文件中批量替换路径。

**Comment by asong2022** [comment]
> 是很麻烦，您可以在json文件中批量替换路径。

嗯嗯！谢谢！
