### ISSUE TITLE
关于路径的建议

### ISSUE THREAD

**Issue by zpoyqx** [LinkScapeOfficial/LinkDown#3]
似乎软件的安装和扩展对视频的保存都是在默认路径下，且无法修改，能不能对它们增加选项可以保存到其他位置

**Comment by TakumiBC** [comment]
我其实以前是写 Python 的，这次 LinkDown for Browsers 的开发使我不得不在一周内学会开发附加组件的各种知识，我需要一段时间调整一下才能继续学习。

**Comment by zpoyqx** [comment]
谢谢开发者回复，我是从奶酪的文章那边过来的，感觉你们做的项目十分有意义，加油哈
