### ISSUE TITLE
厉害啊，不过希望下个版本搞个便携版

### ISSUE THREAD

**Issue by zhucezhifeng** [LinkScapeOfficial/LinkDown#4]
厉害啊，不过希望下个版本搞个便携版

**Comment by 0tianlong520** [comment]
赞👍

**Comment by TakumiBC** [comment]
本項目的初衷就是自動配置環境，而便携版會使軟件無法自動配置環境，使本項目失去意義，故不會推出便携版（除非有技術突破）

**Comment by xingyujie** [comment]
有https://github.com/xingyujie/binpython（doge

**Comment by EdwardLab** [comment]
有https://github.com/xingyujie/binpython

**Comment by TakumiBC** [comment]
@xingyujie  问题的LinkDown没法自动配置Path了
